name: wolt_modal_sheet
description: This package provides a responsive modal with multiple pages, motion animation for page transitions, and scrollable content within each page.
version: 0.5.0
repository: https://github.com/woltapp/wolt_modal_sheet

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: '>=3.7.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ">=6.0.0"

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^2.0.1
  # Flutter test tools
  flutter_test:
    sdk: flutter
  # Test lib.
  test: ^1.18.2
  melos: ^3.1.1
